In [ ]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split

In [ ]:
inputs = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                  [69,96,70]],dtype="float32")

In [ ]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
targets = np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype="float32")

In [ ]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [ ]:
inputs=torch.from_numpy(inputs)   #converting from numpy to torch
targets=torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# weights and biases
w=torch.randn(2,3,requires_grad=True) #to create a weight matrix of 2 rows and 3 columns
b=torch.randn(2,requires_grad=True) # to create a bias matrix of 3 columns
print(w)
print(b)

tensor([[ 0.7331,  0.2489,  0.0570],
        [-0.5017, -0.0300,  0.0174]], requires_grad=True)
tensor([-0.5634,  2.6708], requires_grad=True)


In [ ]:
inputs.dtype

torch.float32

In [ ]:
w.dtype

torch.float32

In [ ]:
def model(x):
    return  x @ w.t() + b

In [ ]:
preds= model(inputs)
print(preds)

tensor([[ 72.0797, -35.2173],
        [ 91.6991, -44.5131],
        [ 99.8750, -43.9920],
        [ 87.0237, -49.1504],
        [ 77.9042, -33.6115]], grad_fn=<AddBackward0>)


In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
#MSE
def mse(p,t):
  diff=p-t
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
loss = mse(preds,targets)
print(loss)

tensor(9987.9736, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.7331,  0.2489,  0.0570],
        [-0.5017, -0.0300,  0.0174]], requires_grad=True)
tensor([[  1076.8746,    -31.4125,    183.2189],
        [-11127.6777, -12385.3613,  -7594.6172]])


In [ ]:
print(b)
print(b.grad)

tensor([-0.5634,  2.6708], requires_grad=True)
tensor([   9.5164, -133.2968])


In [ ]:
with torch.no_grad():
  w-=w.grad* 1e-5
  b-=b.grad* 1e-5
  w.grad.zero_()
  b.grad.zero_()


In [ ]:
print(w)
print(b)
#₹

tensor([[ 0.7223,  0.2492,  0.0551],
        [-0.3904,  0.0938,  0.0933]], requires_grad=True)
tensor([-0.5635,  2.6722], requires_grad=True)


In [ ]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(6927.1680, grad_fn=<DivBackward0>)


In [ ]:
for i in range(10000):
  preds=model(inputs)
  loss= mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
preds=model(inputs)
loss= mse(preds,targets)
print(loss)

tensor(0.5858, grad_fn=<DivBackward0>)


In [ ]:
preds

tensor([[ 57.0698,  70.7566],
        [ 82.2665, 100.3895],
        [118.7089, 132.8858],
        [ 21.0936,  36.9589],
        [101.9048, 119.2096]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
#Iplementing the same above fuctionalities with torch.nn

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37], [69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37],
                   [69, 96, 70], [73, 67, 43], [91, 88, 64],
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133],
                    [22, 37], [103, 119], [56, 70],
                    [81, 101], [119, 133], [22, 37],
                    [103, 119], [56, 70], [81, 101],
                    [119, 133], [22, 37], [103, 119]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]                               #makes dataset object with mapped preds and targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size=5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)  # data passed in batches

In [ ]:
model=nn.Linear(3,2)                                 # initialize weights and biases
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1481, -0.3298,  0.3647],
        [-0.3670, -0.2553,  0.2568]], requires_grad=True)
Parameter containing:
tensor([0.3300, 0.3224], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1481, -0.3298,  0.3647],
         [-0.3670, -0.2553,  0.2568]], requires_grad=True),
 Parameter containing:
 tensor([0.3300, 0.3224], requires_grad=True)]

In [ ]:
preds=model(inputs)                     # passing inputs in model to perform matrix multiplication
preds

tensor([[  4.7290, -32.5354],
        [  8.1281, -39.1111],
        [ -9.8231, -50.9288],
        [ 14.7519, -38.5922],
        [  4.4189, -31.5383],
        [  4.7290, -32.5354],
        [  8.1281, -39.1111],
        [ -9.8231, -50.9288],
        [ 14.7519, -38.5922],
        [  4.4189, -31.5383],
        [  4.7290, -32.5354],
        [  8.1281, -39.1111],
        [ -9.8231, -50.9288],
        [ 14.7519, -38.5922],
        [  4.4189, -31.5383]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(preds,targets)

In [ ]:
loss

tensor(12665.5625, grad_fn=<MseLossBackward0>)

In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)  # weights optimization

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):       #def fit model
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1)%10==0:
       print("Epoch ..............[{}/{}], Loss: {:.4f}".format(epoch+1,num_epochs, loss.item()))

In [ ]:
fit(100,model,loss_fn,opt,train_dl)

Epoch ..............[10/100], Loss: 289.9212
Epoch ..............[20/100], Loss: 73.6988
Epoch ..............[30/100], Loss: 98.2165
Epoch ..............[40/100], Loss: 72.8809
Epoch ..............[50/100], Loss: 145.7097
Epoch ..............[60/100], Loss: 20.2630
Epoch ..............[70/100], Loss: 45.6732
Epoch ..............[80/100], Loss: 33.4290
Epoch ..............[90/100], Loss: 31.3397
Epoch ..............[100/100], Loss: 22.4641


In [ ]:
preds=model(inputs)

In [ ]:
preds

tensor([[ 58.6613,  71.2688],
        [ 83.3808, 100.2011],
        [114.0297, 132.4554],
        [ 29.1486,  42.1857],
        [ 99.2899, 115.3710],
        [ 58.6613,  71.2688],
        [ 83.3808, 100.2011],
        [114.0297, 132.4554],
        [ 29.1486,  42.1857],
        [ 99.2899, 115.3710],
        [ 58.6613,  71.2688],
        [ 83.3808, 100.2011],
        [114.0297, 132.4554],
        [ 29.1486,  42.1857],
        [ 99.2899, 115.3710]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
model(torch.tensor([[75,63,44.]]))

tensor([[55.8715, 68.5040]], grad_fn=<AddmmBackward0>)